version: 0.2
phases:
  install:
    commands:
      - echo No dependencies to install for static website.
  build:
    commands:
      - echo Building frontend (no actual build needed for static files)
  post_build:
    commands:
      - echo Preparing files for deployment
artifacts:
  files:
    - frontend/**/*  