version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install

  build:
    commands:
      - echo No build step required for plain HTML and JavaScript

  post_build:
    commands:
      - echo Deploying to S3
      - aws s3 rm s3://photo-search-app-nyu-2024 --recursive  # Remove existing files
      - aws s3 cp frontend/ s3://photo-search-app-nyu-2024 --recursive  # Copy new files
      - echo Frontend deployment completed

artifacts:
  files:
    - 'frontend/**'